#application config
development:
  OcuID: "97e7ded242a95b762a1c74200523af5c"
  OcuKey: "50d162f720f7c5100ef64f53daf10b65"
  host: "http://192.168.100.20:3001"
  server_host: "http://192.168.100.20:3000"
  domain: "dehui220.com.cn"
  imap:
    address: "mail.dehui220.com.cn"
    port: 993
    enable_ssl: true
  smtp:
    address: "mail.dehui220.com.cn"
    port: 465
    openssl_verify_mode: "none"
    authentication : "login"
    enable_starttls_auto : true
test:

production:
  OcuID: "97e7ded242a95b762a1c74200523af5c"
  OcuKey: "50d162f720f7c5100ef64f53daf10b65"
  host: "http://m.dehuinet.com:3001"
  server_host: "http://dev.dehuinet.com:81"
  domain: "dehui220.com.cn"
  imap:
    address: "mail.dehui220.com.cn"
    port: 993
    enable_ssl: true
  smtp:
    address: "mail.dehui220.com.cn"
    port: 465
    openssl_verify_mode: "none"
    authentication : "login"
    enable_starttls_auto : true
