#application config
development:
  OcuID: "97e7ded242a95b762a1c74200523af5c"
  OcuKey: "50d162f720f7c5100ef64f53daf10b65"
  host: "http://192.168.100.20:3001"
  server_host: "http://192.168.100.20:3000"
  domain: "dehui220.com.cn"
  admin_mail: "MinyouAdmin@dehui220.com.cn"
  admin_password: "5ec218c78cb8b5d6d18040e2b35d91a4"
  imap:
    address: "mail.dehui220.com.cn"
    port: 993
    enable_ssl: true
  smtp:
    address: "mail.dehui220.com.cn"
    port: 465
    openssl_verify_mode: "none"
    authentication : "login"
    enable_starttls_auto : true
test:

production:
  OcuID: "a0353b3417f22f1de30a836ba6ac3400"
  OcuKey: "b2b6acb1b01044c3bd611e51c1e2fc3c"
  host: "http://m.dehuinet.com:3001"
  server_host: "http://huatai.dehuinet.com:84"
  domain: "dehui220.com.cn"
  admin_mail: "MinyouAdmin@dehui220.com.cn"
  admin_password: "5ec218c78cb8b5d6d18040e2b35d91a4"
  imap:
    address: "192.168.100.220"
    port: 993
    enable_ssl: true
  smtp:
    address: "192.168.100.220"
    port: 465
    openssl_verify_mode: "none"
    authentication : "login"
    enable_starttls_auto : true
